CREATE TABLE Docs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  user_id UUID NOT NULL UNIQUE,
  sheet_id TEXT NOT NULL,
  account TEXT NOT NULL,
  address1 TEXT NOT NULL,
  address2 TEXT NOT NULL,
  bank TEXT NOT NULL,
  city TEXT NOT NULL,
  company TEXT NOT NULL,
  nip TEXT NOT NULL
);
CREATE POLICY "Enable access to authors" ON public.Docs FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);