DROP TABLE IF EXISTS sheets;
DROP TABLE IF EXISTS invoices;
DROP TABLE IF EXISTS reports;

CREATE TABLE sheets (
  account TEXT NOT NULL,
  address1 TEXT NOT NULL,
  address2 TEXT NOT NULL,
  bank TEXT NOT NULL,
  city TEXT NOT NULL,
  company TEXT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  nip TEXT NOT NULL,
  userId UUID NOT NULL UNIQUE REFERENCES auth.users on delete cascade
);
CREATE POLICY "Enable access to authors" ON public.sheets FOR ALL USING (auth.uid() = userId) WITH CHECK (auth.uid() = userId);

CREATE TABLE invoices (
  address1 TEXT NOT NULL,
  address2 TEXT NOT NULL,
  company TEXT NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
  date TIMESTAMP NOT NULL,
  hours BIGINT NOT NULL,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  nip TEXT NOT NULL,
  price BIGINT NOT NULL,
  sheetId BIGINT NOT NULL REFERENCES public.sheets on delete cascade,
  title TEXT NOT NULL
);

CREATE TABLE reports (
  accidentPremium BIGINT NOT NULL,
  date TIMESTAMP NOT NULL,
  disabilityPension BIGINT NOT NULL,
  healthContributions BIGINT NOT NULL,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pensionContribution BIGINT NOT NULL,
  sheetId BIGINT NOT NULL REFERENCES public.sheets on delete cascade,
  sicknessContribution BIGINT NOT NULL,
  socialSecurity BIGINT NOT NULL
);